---
- name: check existing local network
  shell: docker network ls | grep -q local
  register: net_local
  changed_when: false
  failed_when: net_local.rc == 2

- name: ensure local network exists
  command: docker network create local
  when: net_local.rc == 1

- name: directory for keepass configuration should exist
  file: path=/opt/keepass state=directory

- name: update keepass configuration
  template: src=keepass-node-config.js.j2 dest=/opt/keepass/keepass-node-config.js
  register: keepass_config
  become: yes
  become_user: root

- name: check existing keepass volume
  shell: docker volume ls | grep -q keepass
  register: vol_keepass
  changed_when: false
  failed_when: vol_keepass.rc == 2

- name: ensure keepass volume exists
  command: docker volume create --name keepass
  when: vol_keepass.rc == 1

- name: start keepass container
  docker:
    image: "{{keepass_image}}"
    pull: always
    name: "{{keepass_container}}"
    volumes:
      - "/opt/keepass/keepass-node-config.js:/keepass/keepass-node-config.js:ro"
      - "keepass:/keepass/local"
    volumes_from: "{{keepass_data_container}}"
    expose: "{{keepass_port_intern}}/tcp"
    net: local
    state: reloaded
    restart_policy: unless-stopped
