[context.production.environment]
  HUGO_VERSION = "0.119.0"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture -s site -b / -t congo-2.7.6"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.119.0"

[[redirects]]
  # this is the default path used by IONOS/1&1
  from = "/defaultsite"
  to = "/"
#  status = 301
#  force = false

[[redirects]]
  # /post was for the vienna theme, /posts is for the congo theme
  from = "/post/*"
  to = "/posts/:splat"
#  status = 301
#  force = false
