[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture -s site -b / -t vienna"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.85.0"

[[redirects]]
  # this is the default path used by IONOS/1&1
  from = "/defaultsite"
  to = "/"
#  status = 301
#  force = false
