---
- name: install apt-transport-https
  apt: name=apt-transport-https state=latest update_cache=yes cache_valid_time=86400
- name: add key for new apt repository
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present
- name: add new apt repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-precise main" state=present update_cache=yes
# TODO explicitly configure the desired storage driver (currently OverlayFS)
- name: install docker
  apt: name=docker-engine state=present
- name: make docker service start on boot
  service: name=docker enabled=yes
- name: start docker service
  service: name=docker state=started
