baseurl = "https://www.gesellix.net"
title = "gesellix.net"
copyright = "&copy; Tobias Gesellchen"

[params]
  subtitle = "a senior hipster developer blog"
  twitter = "gesellix"
  github = "gesellix"
#  stackoverflow = "372019"
#  linkedin = "gesellix"
#  xing = "Tobias_Gesellchen"
#  googleplus = "TobiasGesellchen"
  ga_api_key = "UA-45011104-1"
