---
- name: collect docker facts
  docker_facts:
    names:
      - dns
      - blog
      - keepass
  register: docker_facts

- debug: var=inspected
- debug: var=container_env

#- name: check if DNS_ADDR has changed

- name: is the same
  debug: msg="same"
  when: inspected['blog'] is defined and ('0.10.39' == container_env['blog']['NODE_VERSION'])

- name: not the same
  debug: msg="not the same"
  when: inspected['blog'] is defined and (inspected['blog'].NetworkSettings.IPAddress != container_env['blog']['FOO'])
