---
# http://docs.ansible.com/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
# `mkpasswd --method=SHA-512`
# `docker run --rm -it ubuntu:14.04 bash -c "apt-get update; apt-get install -y whois; mkpasswd --method=SHA-512"`
# `docker run --rm -it alpine:3.2 sh -c "apk update; apk add -U -t makepasswd; mkpasswd"`
- name: create robot user
  user: >
    name=robot
    group=users
    groups=docker,sudo
    password=$6$guHHwwoJz8QTFjCL$Ha0kVlKqfffym8SGVOWaK5xh/9NIVUIf6nJiM.IVRC84zoUA4w5qEFmxeZHlEM4fsPwtfSySMs77rVhdfG5Kn/
    shell=/bin/bash
- authorized_key: user=robot state=present manage_dir=yes key="{{item}}"
  with_file:
    - public_keys/gesellix.pub
    - public_keys/gesellix-mac.pub
    - public_keys/gesellix-win.pub
- name: create user "gesellix"
  user: >
    name=gesellix
    group=users
    groups=docker,sudo
    password=$6$hsZyhOI4S08Cf6li$8wkAw.LA8CnWphwldZvwit6LQp3ehUG8/P3wG/5hk1E7G9QHg3jmecNyn.1HiOXX9Zqwwxs9flsS4tR5ed2dr0
    shell=/bin/bash
- authorized_key: user=gesellix state=present manage_dir=yes key="{{item}}"
  with_file:
    - public_keys/gesellix.pub
    - public_keys/gesellix-mac.pub
    - public_keys/gesellix-win.pub
