---
name: 'Update GitHub Profile'
on:
  workflow_dispatch:
  push:
  schedule:
    # Every 5 hours.
    # https://crontab.guru/#0_*/5_*_*_*
    - cron: '0 */5 * * *'
jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          docker run --rm \
            -e GITHUB_TOKEN \
            -v "${{ github.workspace }}:/github/workspace" \
            -w /github/workspace \
            ghcr.io/gesellix/markscribe:latest -write README.md README.md.tpl
      - uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[bot] Update README.md"
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
...
