---
name: 'Update GitHub Profile'
on:
  workflow_dispatch:
  push:
  schedule:
    # Every hour.
    # https://crontab.guru/#0_*/1_*_*_*
    - cron: '0 */1 * * *'
jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@@v2
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[bot] Update README.md"
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
...
